---
title: ""
author: ""
date: ""
output: pdf_document
---

```{r library, echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE, results='hide'}
library(ggplot2)       # for generating plots
library(latex2exp)     # for plot text latex
library(cowplot)       # for merging plots
library(gridExtra)     # for griding plots
library(grid)          # for griding plots
library(stringr)       # for uppercase first letter
```

```{r mu_k_all, echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE}
param_plt <- data.frame()
# load AO parameter trio
vec_process <- c('influent','anoxic','oxic','effluent')
for(item in vec_process){
  file_in <- paste0('../../../output/AO_ASV/param_trio_asv_',item,'.RData')
  load(file_in)
  param_trio$ID <- rownames(param_trio)
  # extract poisson distributed microbes
  param_poisson <- param_trio[param_trio$k==Inf,]
  # extract gamma-poisson distributed microbes
  param_gpm <- param_trio[param_trio$k!=Inf,]
  # extract zero-inflated microbes
  param_zeroinf <- param_trio[param_trio$pi0!=0,]
  # annotate procedure
  param_gpm$Procedure <- str_to_title(item)
  param_plt <- rbind(param_plt, param_gpm)
}

# load HZ parameter trio
vec_process <- c('bay','era')
for(item in vec_process){
  file_in <- paste0('../../../output/HZ/param_trio_',item,'.RData')
  load(file_in)
  param_trio$ID <- rownames(param_trio)
  # extract poisson distributed microbes
  param_poisson <- param_trio[param_trio$k==Inf,]
  # extract gamma-poisson distributed microbes
  param_gpm <- param_trio[param_trio$k!=Inf,]
  # extract zero-inflated microbes
  param_zeroinf <- param_trio[param_trio$pi0!=0,]
  # annotate procedure
  param_gpm$Procedure <- str_to_title(item)
  param_plt <- rbind(param_plt, param_gpm)
}

rownames(param_plt) <- c(1:nrow(param_plt))
param_plt$Procedure <- ifelse(param_plt$Procedure=='Era','ERA',param_plt$Procedure)

param_plt$Procedure <- factor(param_plt$Procedure,
                              levels=c('Bay','Influent','Oxic', 
                                       'ERA','Anoxic','Effluent'))

param_plt$mu_up <- 4.457417
param_plt$mu_up <- ifelse(param_plt$Procedure=='ERA', 
                          4.881282, param_plt$mu_up)
param_plt$mu_up <- ifelse(param_plt$Procedure=='Influent', 
                          7.142101, param_plt$mu_up)
param_plt$mu_up <- ifelse(param_plt$Procedure=='Anoxic', 
                          5.209871, param_plt$mu_up)
param_plt$mu_up <- ifelse(param_plt$Procedure=='Oxic', 
                          4.299989, param_plt$mu_up)
param_plt$mu_up <- ifelse(param_plt$Procedure=='Effluent', 
                          4.405847, param_plt$mu_up)


param_plt$k_low <- 10.452344
param_plt$k_low <- ifelse(param_plt$Procedure=='ERA', 
                          10.452344, param_plt$k_low)
param_plt$k_low <- ifelse(param_plt$Procedure=='Influent', 
                          8.844581, param_plt$k_low)
param_plt$k_low <- ifelse(param_plt$Procedure=='Anoxic', 
                          8.673801, param_plt$k_low)
param_plt$k_low <- ifelse(param_plt$Procedure=='Oxic', 
                          8.673801, param_plt$k_low)
param_plt$k_low <- ifelse(param_plt$Procedure=='Effluent', 
                          8.812485, param_plt$k_low)


g1 <- ggplot() +
  geom_point(data=param_plt, 
             aes(x=log(k), y=log(mu), color=pi0),alpha=0.6,size=0.24) +
  geom_vline(data=param_plt, aes(xintercept = mu_up), 
             linetype="dotdash", color = "black", size=0.12) +
  geom_vline(data=param_plt, aes(xintercept = k_low), 
             linetype="dotdash", color = "black", size=0.12) +
  ylab(TeX('\\log{(\\hat{\\mu})}')) +
  xlab(TeX('\\log{(\\hat{k})}')) +
  ggtitle(TeX('')) +
  xlim(-5,20) +
  ylim(-5,10) +
  theme_bw() +
  theme(aspect.ratio=1) +
  scale_color_continuous(type = "viridis") +
  facet_wrap(Procedure~., scale='free', nrow=2) +
  labs(color=TeX('$\\hat{\\pi}_0$')) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.text.x = element_text(size = 9, vjust = 0.5, hjust = 0),
        axis.text.y = element_text(size=9),
        strip.text = element_text(size = 12),
        legend.title = element_text(color = "black", size = 12),
        legend.text = element_text(color = "black", size = 9))

g1
```










