---
title: ""
author: ""
date: ""
output: pdf_document
---

```{r library, echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE, results='hide'}
library(ggplot2)       # for generating plots
library(latex2exp)     # for plot text latex
library(cowplot)       # for merging plots
library(gridExtra)     # for griding plots
library(grid)          # for griding plots
library(stringr)       # for uppercase first letter
library(matrixStats)   # for matrix computations

get_legend <- function(p){
  tmp <- ggplot_gtable(ggplot_build(p))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  legend
}
```

```{r prepare, echo=FALSE, eval=FALSE, warning=FALSE, message=FALSE}
# run mu_k_ao_category.Rmd
# run mu_k_hz_category.Rmd
```

```{r mu_k_ao_category, echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE}
# load parameters mle
vec_process <- c('influent','anoxic','oxic','effluent')
param_plt <- data.frame()
for(item in vec_process){
  load(paste0('../../../output/AO_ASV/param_trio_asv_',item,'.RData'))
  param_trio$ID <- rownames(param_trio)
  # extract gamma-poisson distributed microbes
  param_gpm <- param_trio[param_trio$k!=Inf,]
  # annotate procedure
  param_gpm$Procedure <- str_to_title(item)
  # annotate taxa category
  load(paste0('../../../output/AO_ASV/taxa_category_',item,'.RData'))
  param_gpm$Category <- ifelse(param_gpm$ID %in% id_rt, 'RT', 'Other')
  param_gpm$Category <- ifelse(param_gpm$ID %in% id_mt, 'IT', param_gpm$Category)
  param_gpm$Category <- ifelse(param_gpm$ID %in% id_at, 'AT', param_gpm$Category)
  param_gpm$Category <- ifelse(param_gpm$ID %in% id_crt, 'CRT', param_gpm$Category)
  param_gpm$Category <- ifelse(param_gpm$ID %in% id_cat, 'CAT', param_gpm$Category)
  param_gpm$Category <- ifelse(param_gpm$ID %in% id_crat, 'CRAT', param_gpm$Category)
  
  param_plt <- rbind(param_plt, param_gpm)

}

vec_process <- c('bay','era')
for(item in vec_process){
  load(paste0('../../../output/HZ/param_trio_',item,'.RData'))
  param_trio$ID <- rownames(param_trio)
  # extract gamma-poisson distributed microbes
  param_gpm <- param_trio[param_trio$k!=Inf,]
  # annotate procedure
  param_gpm$Procedure <- str_to_title(item)
  # annotate taxa category
  load(paste0('../../../output/HZ/taxa_category_',item,'.RData'))
  param_gpm$Category <- ifelse(param_gpm$ID %in% id_rt, 'RT', 'Other')
  param_gpm$Category <- ifelse(param_gpm$ID %in% id_mt, 'IT', param_gpm$Category)
  param_gpm$Category <- ifelse(param_gpm$ID %in% id_at, 'AT', param_gpm$Category)
  param_gpm$Category <- ifelse(param_gpm$ID %in% id_crt, 'CRT', param_gpm$Category)
  param_gpm$Category <- ifelse(param_gpm$ID %in% id_cat, 'CAT', param_gpm$Category)
  param_gpm$Category <- ifelse(param_gpm$ID %in% id_crat, 'CRAT', param_gpm$Category)
  
  param_plt <- rbind(param_plt, param_gpm)

}

rownames(param_plt) <- c(1:nrow(param_plt))
param_plt$Procedure <- ifelse(param_plt$Procedure=='Era','ERA',param_plt$Procedure)

param_plt$Procedure <- factor(param_plt$Procedure,
                              levels=c('Bay','Influent','Oxic', 
                                       'ERA','Anoxic','Effluent'))
param_plt$Category <- factor(param_plt$Category,
                             levels=c('AT','CAT','CRAT',
                                      'IT','CRT','RT'))

ggplot() +
  geom_point(data=param_plt, 
             aes(x=log(k), y=log(mu), color=Category), alpha=0.6,size=0.6) +
  geom_point(data=param_plt[param_plt$Category=='IT',], 
             aes(x=log(k), y=log(mu), color=Category), alpha=0.6,size=0.6) +
  ylab(TeX('\\log{(\\hat{\\mu})}')) +
  xlab(TeX('\\log{(\\hat{k})}')) +
  ggtitle(TeX('')) +
  xlim(-5,20) +
  ylim(-5,10) +
  theme_bw() +
  theme(aspect.ratio=1) +
  facet_wrap(Procedure~., scale='free') +
  scale_colour_manual(values = c('#e41a1c','#e78ac3','#ffd92f',
                                 '#984ea3','#b3de69','#80b1d3')) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_text(size = 12),
        axis.title.y = element_text(size = 12),
        axis.text.x = element_text(size = 9, vjust = 0.5, hjust = 0),
        axis.text.y = element_text(size=9),
        strip.text = element_text(size = 12),
        legend.title = element_text(color = "black", size = 12),
        legend.text = element_text(color = "black", size = 9)) +
  guides(color = guide_legend(override.aes = list(size = 1.8)))

```








