---
title: ""
author: ""
date: ""
output: pdf_document
---

```{r library, echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE, results='hide'}
#install.packages('devtools')
#library(devtools)
#devtools::install_github("gavinsimpson/ggvegan")

library(ggplot2)       # for generating plots
library(latex2exp)     # for plot text latex
library(cowplot)       # for merging plots
library(gridExtra)     # for griding plots
library(grid)          # for griding plots
library(stringr)       # for uppercase first letter
library(ggh4x)         # for grid plot with free axis
library(vegan)         # for example data in pcoa analysis
library(ggvegan)       # for ggplot vegan results

get_legend <- function(p){
  tmp <- ggplot_gtable(ggplot_build(p))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  legend
}
```

```{r prepare, echo=FALSE, eval=FALSE, warning=FALSE, message=FALSE}
sapply(list.files(pattern="[.]R$", path="../../R/PMCosm", full.names=TRUE), source)
# load environment factors
env <- read.csv('../../data/AO/env_factors.csv',row.names=1)
# load abundance data
mic <- read.table('../../data/AO/OTU_table.txt')
id_dye <- c('LS','SF','CZ','BA','YF')
id_med <- c('GB','YTSW','XHC','ZC')
id_pes <- c('YT','YN')
lis_ind <- list(id_dye, id_med, id_pes)
names(lis_ind) <- c('Dye','Medicine','Pesticide')

id_inf <- c('Inf1','Inf2','Inf3')
id_axi <- c('Ax1','Ax2','Ax3')
id_oxi <- c('Ox1','Ox2','Ox3')
id_eff <- c('Eff1','Eff2','Eff3')
lis_pro <- list(id_inf, id_axi, id_oxi, id_eff)
names(lis_pro) <- c('Influent','Anoxic','Oxic','Effluent')

for(region in 1:4){
  # extract column id
  id_col <- c()
  for(i in 1:length(lis_ind)){
    id_ind <- lis_ind[[i]]
    id_pro <- lis_pro[[region]]
    id_col <- c(id_col, paste0(rep(id_ind, each=length(id_pro)),'_',rep(id_pro, length(id_ind))))
  }
  # extract row id
  load(paste0('../../output/AO/taxa_category_',tolower(names(lis_pro)[region]),'.RData'))
  load(paste0('../../output/AO/param_trio_',tolower(names(lis_pro)[region]),'.RData'))
  param_trio <- param_trio[param_trio$k!=Inf,]
  id_mu_wing <- rownames(param_trio[param_trio$k<exp(7),])
  id_k_wing <- rownames(param_trio[param_trio$k>exp(7),])
  # extract abundance data
  mic_rt <- mic[intersect(id_rt,id_mu_wing), id_col]
  mic_crt <- mic[intersect(id_crt,id_mu_wing), id_col]
  
  # cca analysis
  # original data set, species on columns
  cc_rt  <- cca(t(mic_rt),  env[id_col,]) 
  cc_crt <- cca(t(mic_crt), env[id_col,])
  save(cc_rt, cc_crt, 
       file=paste0('../../output/AO/cca_rt_nrt_mu_',tolower(names(lis_pro)[region]),'.RData'))
} 
  
```

```{r cca_plot, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
load('../../output/AO/cca_rt_nrt_mu_influent.RData')
cc_rt_influent <- cc_rt
cc_crt_influent <- cc_crt

load('../../output/AO/cca_rt_nrt_mu_anoxic.RData')
cc_rt_anoxic <- cc_rt
cc_crt_anoxic <- cc_crt

load('../../output/AO/cca_rt_nrt_mu_oxic.RData')
cc_rt_oxic <- cc_rt
cc_crt_oxic <- cc_crt

load('../../output/AO/cca_rt_nrt_mu_effluent.RData')
cc_rt_effluent <- cc_rt
cc_crt_effluent <- cc_crt


g_inf_rt <- autoplot(cc_rt_influent) +
  theme_bw() +
  xlab(TeX('CCA1')) +
  ylab(TeX('CCA2')) +
  ggtitle(TeX('Influent RT')) +
  theme(plot.title=element_text(size = 10, hjust = 0.5),
        legend.position = c(0.8,0.8),
        aspect.ratio=1,
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 6),
        axis.text.y = element_text(size = 6),
        legend.title = element_text(color = "black", size = 9),
        legend.text = element_text(color = "black", size = 7))

g_inf_crt <- autoplot(cc_crt_influent) +
  theme_bw() +
  xlab(TeX('CCA1')) +
  ylab(TeX('CCA2')) +
  ggtitle(TeX('Influent CRT')) +
  theme(plot.title=element_text(size = 10, hjust = 0.5),
        legend.position = "none",
        aspect.ratio=1,
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 6),
        axis.text.y = element_text(size = 6),
        legend.title = element_text(color = "black", size = 9),
        legend.text = element_text(color = "black", size = 7))


g_ano_rt <- autoplot(cc_rt_anoxic) +
  theme_bw() +
  xlab(TeX('CCA1')) +
  ylab(TeX('CCA2')) +
  ggtitle(TeX('Anoxic RT')) +
  theme(plot.title=element_text(size = 10, hjust = 0.5),
        legend.position = "none",
        aspect.ratio=1,
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 6),
        axis.text.y = element_text(size = 6),
        legend.title = element_text(color = "black", size = 9),
        legend.text = element_text(color = "black", size = 7))

g_ano_crt <- autoplot(cc_crt_anoxic) +
  theme_bw() +
  xlab(TeX('CCA1')) +
  ylab(TeX('CCA2')) +
  ggtitle(TeX('Anoxic CRT')) +
  theme(plot.title=element_text(size = 10, hjust = 0.5),
        legend.position = "none",
        aspect.ratio=1,
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 6),
        axis.text.y = element_text(size = 6),
        legend.title = element_text(color = "black", size = 9),
        legend.text = element_text(color = "black", size = 7))

g_oxi_rt <- autoplot(cc_rt_oxic) +
  theme_bw() +
  xlab(TeX('CCA1')) +
  ylab(TeX('CCA2')) +
  ggtitle(TeX('Oxic RT')) +
  theme(plot.title=element_text(size = 10, hjust = 0.5),
        legend.position = "none",
        aspect.ratio=1,
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 6),
        axis.text.y = element_text(size = 6),
        legend.title = element_text(color = "black", size = 9),
        legend.text = element_text(color = "black", size = 7))

g_oxi_crt <- autoplot(cc_crt_oxic) +
  theme_bw() +
  xlab(TeX('CCA1')) +
  ylab(TeX('CCA2')) +
  ggtitle(TeX('Oxic CRT')) +
  theme(plot.title=element_text(size = 10, hjust = 0.5),
        legend.position = "none",
        aspect.ratio=1,
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 6),
        axis.text.y = element_text(size = 6),
        legend.title = element_text(color = "black", size = 9),
        legend.text = element_text(color = "black", size = 7))

g_eff_rt <- autoplot(cc_rt_effluent) +
  theme_bw() +
  xlab(TeX('CCA1')) +
  ylab(TeX('CCA2')) +
  ggtitle(TeX('Effluent RT')) +
  theme(plot.title=element_text(size = 10, hjust = 0.5),
        legend.position = "none",
        aspect.ratio=1,
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 6),
        axis.text.y = element_text(size = 6),
        legend.title = element_text(color = "black", size = 9),
        legend.text = element_text(color = "black", size = 7))

g_eff_crt <- autoplot(cc_crt_effluent) +
  theme_bw() +
  xlab(TeX('CCA1')) +
  ylab(TeX('CCA2')) +
  ggtitle(TeX('Effluent CRT')) +
  theme(plot.title=element_text(size = 10, hjust = 0.5),
        legend.position = "none",
        aspect.ratio=1,
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(size = 6),
        axis.text.y = element_text(size = 6),
        legend.title = element_text(color = "black", size = 9),
        legend.text = element_text(color = "black", size = 7))



plot_grid(g_inf_rt, g_ano_rt, nrow=1, align='v')
plot_grid(g_oxi_rt, g_eff_rt, nrow=1, align='v')

plot_grid(g_inf_crt, g_ano_crt, nrow=1, align='v')
plot_grid(g_oxi_crt, g_eff_crt, nrow=1, align='v')


```









